//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        public int itemId { get; set; }
        public string itemPlace { get; set; }
        public Nullable<int> categoryCode { get; set; }
        public string itemDescription { get; set; }
        public string nameFinder { get; set; }
        public string phoneFinder { get; set; }
        public Nullable<bool> isBargain { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<int> imageCode { get; set; }
        public Nullable<int> ImageId { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<int> colorId { get; set; }
    
        public virtual category category { get; set; }
        public virtual color color { get; set; }
        public virtual Image Image { get; set; }
        public virtual users users { get; set; }
    }
}
